on:
  push:
    paths:
      - 'quotes.txt'

jobs:
  update_quotes:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install jq
      run: sudo apt-get install jq
    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Update quotes.json with new quotes from quotes.txt
      run: |
        # Get the current number of lines in quotes.txt
        lines_count_txt=$(wc -l < quotes.txt)
        # Get the current number of quotes in quotes.json
        lines_count_json=$(jq '.quotes | length' quotes.json)
        # Get the new lines from quotes.txt
        new_lines=$(tail -n +$((lines_count_json + 1)) quotes.txt)
        # Define the jq command to append new lines
        jq_command="."

        # Loop through the new lines and append them to the jq command
        while read -r line; do
          escaped_line=$(echo "$line" | jq -R .)
          jq_command+=" | .quotes += [$escaped_line]"
        done <<< "$new_lines"

        # Apply the jq command to quotes.json
        jq "$jq_command" quotes.json > quotes_temp.json
        mv quotes_temp.json quotes.json
        # Commit the changes
        git add quotes.json
        git commit -m "Update quotes.json with new quotes"
    - name: Push changes
      env:
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: git push https://${REPO_ACCESS_TOKEN}@github.com/GooglyBlox/wizard-quotes.git
