name: Update README with unique combinations

on:
  push:
    paths:
      - 'images/wizards/images.json'
      - 'quotes.json'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: |
        npm install fs

    - name: Update README
      run: |
        const fs = require('fs');
        
        const imagesJson = JSON.parse(fs.readFileSync('images/wizards/images.json', 'utf-8'));
        const numImages = imagesJson.images.length;

        const quotesJson = JSON.parse(fs.readFileSync('quotes.json', 'utf-8'));
        const numQuotes = quotesJson.quotes.length;

        const totalCombinations = numImages * numQuotes;

        let readme = fs.readFileSync('README.md', 'utf-8');
        readme = readme.replace(/with ~[0-9,]+ \(as of writing\) unique possibilities./, `with ~${totalCombinations.toLocaleString()} (as of writing) unique possibilities.`);
        fs.writeFileSync('README.md', readme);

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with unique combinations count"
        git push
