name: Update README with unique combinations

on:
  push:
    paths-ignore:
      - '.github/**'
  workflow_dispatch:


jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Update README
      run: node .github/scripts/updateReadme.js

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with unique combinations count" || echo "No changes to commit"
        git remote set-url origin https://${{ secrets.MY_PAT }}@github.com/GooglyBlox/wizard-quotes.git
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
